### ISSUE TITLE
Feature Request: Add `client_name` label to `CollectHathSettingsMetricsJob`

### ISSUE THREAD

**Issue by misaka10055** [mixa3607/EH_metrics#2]
I know I'm asking for too many things...but here is the last one:
I mainly use `client_name` to differentiate my Hath clients, and that works fine for `CollectHathStatusMetricsJob` and such. However, for `CollectHathSettingsMetricsJob` the only option is to group by `client_id`, which is a bit confusing if I have multiple clients running:
<img width="336" alt="image" src="https://github.com/mixa3607/EH_metrics/assets/53370265/2fbc6215-bf38-4d00-b0b6-342068ba6c10">
It would be great if a `client_name` label could be added to `CollectHathSettingsMetricsJob` such that the graph would be much more understandable.

**Comment by mixa3607** [comment]
@misaka10055 try v1.1.1

I'm also working on my own implementation of the h@h client with different features. I'll probably post it on github this weekend.
At a minimum, there will be metrics for the speed of reading from the disk and the speed of uploading files to the client, metrics for the number of requests based on geoip, support for http1/2/3, the ability to host it behind nginx or another reverse-proxy, options for force https on download images (by default http, in my country there is a non-illusory chance to get in a party van).
Im will create a new topic on forum when it is usable.

**Comment by misaka10055** [comment]
Thanks for the quick update!

A custom client looks exciting. Looking forward to using it!
